### ISSUE TITLE
where can I save the image

### ISSUE THREAD

**Issue by felipefm** [Sebiann/miku-hatsune-trilium-theme#2]
Hi, thanks for sharing the theme. I have a question, where can I save the image? In which folder?

**Comment by thouger** [comment]
same problem,hhhh

**Comment by XXXJetfireXXX** [comment]
You should download the release and import the .zip archive in a note. That way you'll get the image as well.
However, the theme was broken due to Trilium being updated, so I fixed it and made a pull request just now.

**Comment by thouger** [comment]
> You should download the release and import the .zip archive in a note. That way you'll get the image as well. However, the theme was broken due to Trilium being updated, so I fixed it and made a pull request just now.

thank you reply

**Comment by thouger** [comment]
> You should download the release and import the .zip archive in a note. That way you'll get the image as well. However, the theme was broken due to Trilium being updated, so I fixed it and made a pull request just now.

thank you reply
